version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source yarn dependencies...
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - pwd
artifacts:
  files:
    - '**/*'
  base-directory: dist
